CREATE DATABASE PROJECTS;

USE PROJECTS;

CREATE TABLE CONTACT(
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(80) DEFAULT NULL,
  EMAIL varchar(80) DEFAULT NULL,
  ADDRESS varchar(100) DEFAULT NULL,
  BIRTHDATE date DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

COMMIT;